---
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake release_checks"
matrix:
  allow_failures:
  fast_finish: true
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
gemfile:
  - .gemfile
env:
  - PUPPET_VERSION="~> 3.8" STRICT_VARIABLES="yes"
  - PUPPET_VERSION="~> 4.8" STRICT_VARIABLES="yes"
  - PUPPET_VERSION="~> 4.9" STRICT_VARIABLES="yes"
  - PUPPET_VERSION="~> 4.10" STRICT_VARIABLES="yes"
notifications:
  email: false
