---
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake release_checks"
matrix:
  allow_failures:
  fast_finish: true
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
gemfile:
  - .gemfile
env:
  - PUPPET_VERSION="~> 3.5" STRICT_VARIABLES="yes"
  - PUPPET_VERSION="~> 4.5" STRICT_VARIABLES="yes"
notifications:
  email: false
